version: '3.8'

services:
  iexec-oracle-trigger:
    build: . # Собирает образ из текущей директории, где находится Dockerfile
    container_name: iexec-oracle-trigger # Имя контейнера
    environment:
      # Переменные окружения, которые будут доступны внутри контейнера
      # Их значения будут взяты из файла .env на хост-машине
      PRIVATE_KEY: ${PRIVATE_KEY}
      IEXEC_PASSWORD: ${IEXEC_PASSWORD}
    volumes:
      # Можем смонтировать /var/log, чтобы видеть логи извне контейнера
      - /var/log/iexec_oracle:/var/log/iexec_oracle
    restart: always # Контейнер будет автоматически перезапускаться при сбоях или рестарте Docker
    # Если CronJob - это единственная задача контейнера, он должен быть запущен в режиме CMD ["cron", "-f"]
    # который мы уже прописали в Dockerfile
